# 调试模式：生产环境请关闭此项
debug: true
logger:
  level: debug
database:
  dsn: root:sYY4ikyLf9@(192.168.64.13:31192)/crm?charset=utf8mb4&parseTime=True&loc=Local
server:
  http_port: 8080
jwt:
  secret: 9e8702b0106a8709ce062382095ab163
